import litgen

def bindings_init_wrapper(name: str, binding_code: str = "", glue_code: str = "") -> str:
    wrapper = f"""
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// <litgen_glue_code>  // Autogenerated code below! Do not edit!

{glue_code}

// </litgen_glue_code> // Autogenerated code end
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

void py_init_module_{name}(py::module& m)
{"{"}
    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    // <litgen_pydef> // Autogenerated code below! Do not edit!

{binding_code}

    // </litgen_pydef> // Autogenerated code end
    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
{"}"}
"""
    return wrapper

module_name = "geometry2d"
headers = [
    "pose.hpp",
    "line.hpp"
]

bindings = ""
glue_code = ""
stubs = ""
for header in headers:
    options = litgen.LitgenOptions()
    generated_code = litgen.generate_code_for_file(options, header)

    glue_code += generated_code.glue_code + "\n"
    bindings += generated_code.pydef_code + "\n"
    stubs += generated_code.stub_code + "\n"

bindings = bindings_init_wrapper(module_name, bindings, glue_code)
with open(f"{module_name}_bindings.hpp", "w") as bindings_file:
    bindings_file.write(bindings)

with open(f"{module_name}.pyi", "w") as stub_file:
    stub_file.write(stubs)
