#include <pybind11/pybind11.h>
namespace py = pybind11;

// header files that defines the C++ code we bind
#include "pose.hpp" 
#include "line.hpp"

// autogenerated header that includes the C++ code bindings
#include "geometry2d_bindings.hpp"

PYBIND11_MODULE(pose_module, m) {
    py_init_module_geometry2d(m);
}
