#include <pybind11/pybind11.h>
namespace py = pybind11;

// header file that defines the C++ Pose class
#include "pose.hpp" 

PYBIND11_MODULE(pose_module, m) {
    // autogenerated header that includes the Pose class bindings
    #include "pose_bindings.hpp"
}
